[package]
name = "frog_jump"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "benches"
harness = false

[features]
iterative = []
par = []
recursive = []

[dependencies]
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.6.0"
